[tool.briefcase]
project_name = "discord webhook"
bundle = "net.progrm.discordwebhook"
version = "0.0.1"
url = "https://discordwebhook.progrm.net"
license = "BSD license"
author = 'Jeong Ji Min'
author_email = "jeong@jimin.email"

[tool.briefcase.app.discordwebhook]
formal_name = "discord webhook"
description = "Discord Webhook Send Tool"
icon = "src/discordwebhook/resources/discordwebhook.ico"
sources = ['src/discordwebhook']
requires = ['discord-webhook']


[tool.briefcase.app.discordwebhook.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.discordwebhook.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.discordwebhook.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.discordwebhook.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.discordwebhook.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
icon = "src/discordwebhook/resources/discordwebhook.ico"
